defaults:
  site_name: 'Portfolio'
  facebook_url: "https://www.facebook.com/damian.sliwecki"
  twitter_url: "https://twitter.com/DamianSliwecki"
  linkedin_url: "https://www.linkedin.com/profile/view?id=253953987"
  gravatar_url: "https://pl.gravatar.com/userimage/48495980/d393539c99a4ecf61bd2002ee6a67b51.jpg"
