default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username:
  password:

test:
  <<: *default
  database: test

development:
  <<: *default
  database: development

production:
  <<: *default
  database: production
